CREATE TABLE nacionalidades (
    id INT IDENTITY(1,1) PRIMARY KEY,  
    nombre_pais VARCHAR(100) NOT NULL  
);

INSERT INTO nacionalidades (nombre_pais)
VALUES 
('Afganistán'),
('Albania'),
('Alemania'),
('Andorra'),
('Angola'),
('Antigua y Barbuda'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Azerbaiyán'),
('Bahamas'),
('Bahréin'),
('Bangladesh'),
('Barbados'),
('Bielorrusia'),
('Bélgica'),
('Belice'),
('Benín'),
('Bhután'),
('Bolivia'),
('Bosnia y Herzegovina'),
('Botsuana'),
('Brasil'),
('Brunéi'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Bután'),
('Cabo Verde'),
('Camboya'),
('Camerún'),
('Canadá'),
('Chile'),
('China'),
('Chipre'),
('Colombia'),
('Comoras'),
('Congo'),
('Costa Rica'),
('Croacia'),
('Cuba'),
('Dinamarca'),
('Dominica'),
('Ecuador'),
('Egipto'),
('El Salvador'),
('Emiratos Árabes Unidos'),
('Eslovaquia'),
('Eslovenia'),
('España'),
('Estados Unidos'),
('Estonia'),
('Etiopía'),
('Fiyi'),
('Filipinas'),
('Finlandia'),
('Francia'),
('Gabón'),
('Gambia'),
('Georgia'),
('Ghana'),
('Granada'),
('Grecia'),
('Guatemala'),
('Guinea'),
('Guinea Ecuatorial'),
('Guyana'),
('Haití'),
('Honduras'),
('Hungría'),
('India'),
('Indonesia'),
('Irak'),
('Irlanda'),
('Isla de Pascua'),
('Islas Marshall'),
('Israel'),
('Italia'),
('Jamaica'),
('Japón'),
('Jordania'),
('Kazajistán'),
('Kenia'),
('Kiribati'),
('Kuwait'),
('Laos'),
('Letonia'),
('Líbano'),
('Liberia'),
('Libia'),
('Liechtenstein'),
('Lituania'),
('Luxemburgo'),
('Madagascar'),
('Malasia'),
('Malawi'),
('Maldivas'),
('Malí'),
('Malta'),
('Mauricio'),
('Mauritania'),
('México'),
('Mónaco'),
('Mongolia'),
('Mozambique'),
('Namibia'),
('Nauru'),
('Nepal'),
('Nicaragua'),
('Níger'),
('Nigeria'),
('Noruega'),
('Nueva Zelanda'),
('Omán'),
('Pakistán'),
('Palau'),
('Panamá'),
('Papúa Nueva Guinea'),
('Paraguay'),
('Perú'),
('Polonia'),
('Portugal'),
('Qatar'),
('Reino Unido'),
('República Checa'),
('República Dominicana'),
('República del Congo'),
('Rumanía'),
('Rusia'),
('Ruanda'),
('Samoa'),
('San Cristóbal y Nieves'),
('San Marino'),
('Santo Tomé y Príncipe'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Singapur'),
('Siria'),
('Somalia'),
('Sri Lanka'),
('Sudáfrica'),
('Sudán'),
('Suecia'),
('Suiza'),
('Surinam'),
('Tailandia'),
('Tanzania'),
('Tayikistán'),
('Timor Oriental'),
('Togo'),
('Tonga'),
('Trinidad y Tobago'),
('Túnez'),
('Turquía'),
('Ucrania'),
('Uganda'),
('Uruguay'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabue');
