/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.skyvoyage;

import java.awt.Color;

/**
 *
 * @author Quintero Pinto
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
        setTitle("Pagina Principal");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lateral = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        vuelos = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        vuelos2 = new javax.swing.JButton();
        ventas = new javax.swing.JButton();
        superior = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lateral.setBackground(new java.awt.Color(255, 255, 204));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quintero Pinto\\Documents\\Datos\\Proyectos de Programacion\\Aerolinea\\SkyVoyage\\src\\main\\java\\app\\images\\Icono.png")); // NOI18N

        titulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quintero Pinto\\Documents\\Datos\\Proyectos de Programacion\\Aerolinea\\SkyVoyage\\src\\main\\java\\app\\images\\titulo.png")); // NOI18N

        vuelos.setBackground(new java.awt.Color(255, 255, 204));
        vuelos.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        vuelos.setForeground(new java.awt.Color(0, 0, 0));
        vuelos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quintero Pinto\\Documents\\Datos\\Proyectos de Programacion\\Aerolinea\\SkyVoyage\\src\\main\\java\\app\\images\\vuelos.png")); // NOI18N
        vuelos.setText("Vuelos");
        vuelos.setBorderPainted(false);
        vuelos.setContentAreaFilled(false);
        vuelos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        vuelos.setIconTextGap(10);
        vuelos.setOpaque(true);
        vuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vuelosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vuelosMouseExited(evt);
            }
        });
        vuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vuelosActionPerformed(evt);
            }
        });

        modificar.setBackground(new java.awt.Color(255, 255, 204));
        modificar.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        modificar.setForeground(new java.awt.Color(0, 0, 0));
        modificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quintero Pinto\\Documents\\Datos\\Proyectos de Programacion\\Aerolinea\\SkyVoyage\\src\\main\\java\\app\\images\\modificar.png")); // NOI18N
        modificar.setText("Modificar");
        modificar.setBorderPainted(false);
        modificar.setContentAreaFilled(false);
        modificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        modificar.setIconTextGap(10);
        modificar.setOpaque(true);
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarMouseExited(evt);
            }
        });
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        vuelos2.setBackground(new java.awt.Color(255, 255, 204));
        vuelos2.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        vuelos2.setForeground(new java.awt.Color(0, 0, 0));
        vuelos2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quintero Pinto\\Documents\\Datos\\Proyectos de Programacion\\Aerolinea\\SkyVoyage\\src\\main\\java\\app\\images\\vuelos.png")); // NOI18N
        vuelos2.setText("Ventas");
        vuelos2.setBorderPainted(false);
        vuelos2.setContentAreaFilled(false);
        vuelos2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        vuelos2.setIconTextGap(10);
        vuelos2.setOpaque(true);
        vuelos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vuelos2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vuelos2MouseExited(evt);
            }
        });
        vuelos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vuelos2ActionPerformed(evt);
            }
        });

        ventas.setBackground(new java.awt.Color(255, 255, 204));
        ventas.setFont(new java.awt.Font("Rockwell Condensed", 1, 30)); // NOI18N
        ventas.setForeground(new java.awt.Color(0, 0, 0));
        ventas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quintero Pinto\\Documents\\Datos\\Proyectos de Programacion\\Aerolinea\\SkyVoyage\\src\\main\\java\\app\\images\\boletos.png")); // NOI18N
        ventas.setText("Ventas");
        ventas.setBorderPainted(false);
        ventas.setContentAreaFilled(false);
        ventas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ventas.setIconTextGap(10);
        ventas.setOpaque(true);
        ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ventasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ventasMouseExited(evt);
            }
        });
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lateralLayout = new javax.swing.GroupLayout(lateral);
        lateral.setLayout(lateralLayout);
        lateralLayout.setHorizontalGroup(
            lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateralLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(lateralLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(vuelos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vuelos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        lateralLayout.setVerticalGroup(
            lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateralLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(vuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vuelos2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        background.add(lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        superior.setBackground(new java.awt.Color(255, 255, 204));

        cerrar.setBackground(new java.awt.Color(255, 255, 204));
        cerrar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        cerrar.setForeground(new java.awt.Color(0, 0, 0));
        cerrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Quintero Pinto\\Documents\\Datos\\Proyectos de Programacion\\Aerolinea\\SkyVoyage\\src\\main\\java\\app\\images\\cerrar-sesion.png")); // NOI18N
        cerrar.setText("Cerrar Sesion");
        cerrar.setBorder(null);
        cerrar.setBorderPainted(false);
        cerrar.setContentAreaFilled(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.setDisplayedMnemonicIndex(0);
        cerrar.setFocusPainted(false);
        cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrar.setIconTextGap(15);
        cerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cerrar.setOpaque(true);
        cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout superiorLayout = new javax.swing.GroupLayout(superior);
        superior.setLayout(superiorLayout);
        superiorLayout.setHorizontalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superiorLayout.createSequentialGroup()
                .addContainerGap(699, Short.MAX_VALUE)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        superiorLayout.setVerticalGroup(
            superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        background.add(superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 870, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarActionPerformed

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered

        cerrar.setBackground(Color.GRAY);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        cerrar.setBackground(new Color(255,255,204));        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseExited

    private void vuelosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vuelosMouseEntered
        vuelos.setBackground(Color.GRAY);     // TODO add your handling code here:
    }//GEN-LAST:event_vuelosMouseEntered

    private void vuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vuelosActionPerformed

    private void vuelosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vuelosMouseExited
         vuelos.setBackground(new Color(255,255,204));      // TODO add your handling code here:
    }//GEN-LAST:event_vuelosMouseExited

    private void modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarMouseEntered

    private void modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarMouseExited

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed

    private void vuelos2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vuelos2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_vuelos2MouseEntered

    private void vuelos2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vuelos2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_vuelos2MouseExited

    private void vuelos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vuelos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vuelos2ActionPerformed

    private void ventasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMouseEntered
        ventas.setBackground(Color.GRAY);
    }//GEN-LAST:event_ventasMouseEntered

    private void ventasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMouseExited
        ventas.setBackground(new Color(255,255,204));  
    }//GEN-LAST:event_ventasMouseExited

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton cerrar;
    private javax.swing.JPanel lateral;
    private javax.swing.JLabel logo;
    private javax.swing.JButton modificar;
    private javax.swing.JPanel superior;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton ventas;
    private javax.swing.JButton vuelos;
    private javax.swing.JButton vuelos2;
    // End of variables declaration//GEN-END:variables
}
