/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app;

/**
 *
 * @author Quintero Pinto
 */
public class Avion1 extends javax.swing.JPanel {

    /**
     * Creates new form Avion1
     */
    public Avion1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        C9 = new javax.swing.JButton();
        C10 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        A54 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        A1 = new javax.swing.JButton();
        FondoAvion = new javax.swing.JLabel();
        A4 = new javax.swing.JButton();
        A11 = new javax.swing.JButton();
        A12 = new javax.swing.JButton();
        A13 = new javax.swing.JButton();

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A2.setBackground(new java.awt.Color(255, 255, 255));
        A2.setForeground(new java.awt.Color(0, 0, 0));
        A2.setText("A2");
        Background.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, 30));

        A3.setBackground(new java.awt.Color(255, 255, 255));
        A3.setForeground(new java.awt.Color(0, 0, 0));
        A3.setText("A3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        Background.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, 30));

        A5.setBackground(new java.awt.Color(255, 255, 255));
        A5.setForeground(new java.awt.Color(0, 0, 0));
        A5.setText("A5");
        Background.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, 30));

        A6.setBackground(new java.awt.Color(255, 255, 255));
        A6.setForeground(new java.awt.Color(0, 0, 0));
        A6.setText("A6");
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        Background.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, 30));

        A7.setBackground(new java.awt.Color(255, 255, 255));
        A7.setForeground(new java.awt.Color(0, 0, 0));
        A7.setText("A7");
        Background.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, 30));

        A8.setBackground(new java.awt.Color(255, 255, 255));
        A8.setForeground(new java.awt.Color(0, 0, 0));
        A8.setText("A8");
        Background.add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, 30));

        A9.setBackground(new java.awt.Color(255, 255, 255));
        A9.setForeground(new java.awt.Color(0, 0, 0));
        A9.setText("A9");
        A9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A9ActionPerformed(evt);
            }
        });
        Background.add(A9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, 30));

        B10.setBackground(new java.awt.Color(255, 255, 255));
        B10.setForeground(new java.awt.Color(0, 0, 0));
        B10.setText("B10");
        Background.add(B10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, 30));

        B9.setBackground(new java.awt.Color(255, 255, 255));
        B9.setForeground(new java.awt.Color(0, 0, 0));
        B9.setText("B9");
        Background.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, 30));

        B8.setBackground(new java.awt.Color(255, 255, 255));
        B8.setForeground(new java.awt.Color(0, 0, 0));
        B8.setText("B8");
        Background.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, 30));

        B7.setBackground(new java.awt.Color(255, 255, 255));
        B7.setForeground(new java.awt.Color(0, 0, 0));
        B7.setText("B7");
        Background.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, 30));

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setForeground(new java.awt.Color(0, 0, 0));
        B1.setText("B1");
        Background.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, -1, 30));

        C1.setBackground(new java.awt.Color(255, 255, 255));
        C1.setForeground(new java.awt.Color(0, 0, 0));
        C1.setText("C1");
        Background.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 610, -1, 30));

        B2.setBackground(new java.awt.Color(255, 255, 255));
        B2.setForeground(new java.awt.Color(0, 0, 0));
        B2.setText("B2");
        Background.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, 30));

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setForeground(new java.awt.Color(0, 0, 0));
        B3.setText("B3");
        Background.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, 30));

        B4.setBackground(new java.awt.Color(255, 255, 255));
        B4.setForeground(new java.awt.Color(0, 0, 0));
        B4.setText("B4");
        Background.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, 30));

        B5.setBackground(new java.awt.Color(255, 255, 255));
        B5.setForeground(new java.awt.Color(0, 0, 0));
        B5.setText("B5");
        Background.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, 30));

        C2.setBackground(new java.awt.Color(255, 255, 255));
        C2.setForeground(new java.awt.Color(0, 0, 0));
        C2.setText("C2");
        Background.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, 30));

        C3.setBackground(new java.awt.Color(255, 255, 255));
        C3.setForeground(new java.awt.Color(0, 0, 0));
        C3.setText("C3");
        Background.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, 30));

        C4.setBackground(new java.awt.Color(255, 255, 255));
        C4.setForeground(new java.awt.Color(0, 0, 0));
        C4.setText("C4");
        Background.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, 30));

        C5.setBackground(new java.awt.Color(255, 255, 255));
        C5.setForeground(new java.awt.Color(0, 0, 0));
        C5.setText("C5");
        Background.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, 30));

        C6.setBackground(new java.awt.Color(255, 255, 255));
        C6.setForeground(new java.awt.Color(0, 0, 0));
        C6.setText("C6");
        Background.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, 30));

        C7.setBackground(new java.awt.Color(255, 255, 255));
        C7.setForeground(new java.awt.Color(0, 0, 0));
        C7.setText("C7");
        Background.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, 30));

        C8.setBackground(new java.awt.Color(255, 255, 255));
        C8.setForeground(new java.awt.Color(0, 0, 0));
        C8.setText("C8");
        Background.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, 30));

        C9.setBackground(new java.awt.Color(255, 255, 255));
        C9.setForeground(new java.awt.Color(0, 0, 0));
        C9.setText("C9");
        Background.add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, 30));

        C10.setBackground(new java.awt.Color(255, 255, 255));
        C10.setForeground(new java.awt.Color(0, 0, 0));
        C10.setText("C10");
        Background.add(C10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, 30));

        B6.setBackground(new java.awt.Color(255, 255, 255));
        B6.setForeground(new java.awt.Color(0, 0, 0));
        B6.setText("B6");
        Background.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, 30));

        A54.setBackground(new java.awt.Color(255, 255, 255));
        A54.setForeground(new java.awt.Color(0, 0, 0));
        A54.setText("A4");
        Background.add(A54, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, 30));

        A10.setBackground(new java.awt.Color(255, 255, 255));
        A10.setForeground(new java.awt.Color(0, 0, 0));
        A10.setText("A10");
        Background.add(A10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, 30));

        A1.setBackground(new java.awt.Color(255, 255, 255));
        A1.setForeground(new java.awt.Color(0, 0, 0));
        A1.setText("A1");
        Background.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, -1, 30));

        FondoAvion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo Vuelo.png"))); // NOI18N
        Background.add(FondoAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        A4.setBackground(new java.awt.Color(255, 255, 255));
        A4.setForeground(new java.awt.Color(0, 0, 0));
        A4.setText("A2");
        Background.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, -1, 30));

        A11.setBackground(new java.awt.Color(255, 255, 255));
        A11.setForeground(new java.awt.Color(0, 0, 0));
        A11.setText("A3");
        A11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A11ActionPerformed(evt);
            }
        });
        Background.add(A11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, 30));

        A12.setBackground(new java.awt.Color(255, 255, 255));
        A12.setForeground(new java.awt.Color(0, 0, 0));
        A12.setText("A5");
        Background.add(A12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, 30));

        A13.setBackground(new java.awt.Color(255, 255, 255));
        A13.setForeground(new java.awt.Color(0, 0, 0));
        A13.setText("A6");
        A13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A13ActionPerformed(evt);
            }
        });
        Background.add(A13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A6ActionPerformed

    private void A9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A9ActionPerformed

    private void A11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A11ActionPerformed

    private void A13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A10;
    private javax.swing.JButton A11;
    private javax.swing.JButton A12;
    private javax.swing.JButton A13;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A54;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JPanel Background;
    private javax.swing.JButton C1;
    private javax.swing.JButton C10;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton C9;
    private javax.swing.JLabel FondoAvion;
    // End of variables declaration//GEN-END:variables
}
