/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app;

/**
 *
 * @author Quintero Pinto
 */
public class Avion3 extends javax.swing.JPanel {

    /**
     * Creates new form Avion3
     */
    public Avion3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        A1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A54 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A9 = new javax.swing.JButton();
        A10 = new javax.swing.JButton();
        A55 = new javax.swing.JButton();
        A11 = new javax.swing.JButton();
        A12 = new javax.swing.JButton();
        A13 = new javax.swing.JButton();
        A15 = new javax.swing.JButton();
        A16 = new javax.swing.JButton();
        A17 = new javax.swing.JButton();
        A56 = new javax.swing.JButton();
        A18 = new javax.swing.JButton();
        A19 = new javax.swing.JButton();
        A20 = new javax.swing.JButton();
        A21 = new javax.swing.JButton();
        FondoAvion = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setBackground(new java.awt.Color(255, 255, 255));
        A1.setForeground(new java.awt.Color(0, 0, 0));
        A1.setText("A1");
        background.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, 30));

        A2.setBackground(new java.awt.Color(255, 255, 255));
        A2.setForeground(new java.awt.Color(0, 0, 0));
        A2.setText("A2");
        background.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, 30));

        A3.setBackground(new java.awt.Color(255, 255, 255));
        A3.setForeground(new java.awt.Color(0, 0, 0));
        A3.setText("A3");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        background.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, 30));

        A54.setBackground(new java.awt.Color(255, 255, 255));
        A54.setForeground(new java.awt.Color(0, 0, 0));
        A54.setText("A4");
        background.add(A54, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, 30));

        A5.setBackground(new java.awt.Color(255, 255, 255));
        A5.setForeground(new java.awt.Color(0, 0, 0));
        A5.setText("A5");
        background.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, 30));

        A6.setBackground(new java.awt.Color(255, 255, 255));
        A6.setForeground(new java.awt.Color(0, 0, 0));
        A6.setText("A6");
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        background.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, 30));

        A7.setBackground(new java.awt.Color(255, 255, 255));
        A7.setForeground(new java.awt.Color(0, 0, 0));
        A7.setText("A7");
        background.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, 30));

        A8.setBackground(new java.awt.Color(255, 255, 255));
        A8.setForeground(new java.awt.Color(0, 0, 0));
        A8.setText("A8");
        background.add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, 30));

        A4.setBackground(new java.awt.Color(255, 255, 255));
        A4.setForeground(new java.awt.Color(0, 0, 0));
        A4.setText("B1");
        background.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, 30));

        A9.setBackground(new java.awt.Color(255, 255, 255));
        A9.setForeground(new java.awt.Color(0, 0, 0));
        A9.setText("B2");
        background.add(A9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, 30));

        A10.setBackground(new java.awt.Color(255, 255, 255));
        A10.setForeground(new java.awt.Color(0, 0, 0));
        A10.setText("B3");
        A10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A10ActionPerformed(evt);
            }
        });
        background.add(A10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, 30));

        A55.setBackground(new java.awt.Color(255, 255, 255));
        A55.setForeground(new java.awt.Color(0, 0, 0));
        A55.setText("B4");
        background.add(A55, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, 30));

        A11.setBackground(new java.awt.Color(255, 255, 255));
        A11.setForeground(new java.awt.Color(0, 0, 0));
        A11.setText("B5");
        background.add(A11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, 30));

        A12.setBackground(new java.awt.Color(255, 255, 255));
        A12.setForeground(new java.awt.Color(0, 0, 0));
        A12.setText("B6");
        A12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A12ActionPerformed(evt);
            }
        });
        background.add(A12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, 30));

        A13.setBackground(new java.awt.Color(255, 255, 255));
        A13.setForeground(new java.awt.Color(0, 0, 0));
        A13.setText("B7");
        background.add(A13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, 30));

        A15.setBackground(new java.awt.Color(255, 255, 255));
        A15.setForeground(new java.awt.Color(0, 0, 0));
        A15.setText("C1");
        background.add(A15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, -1, 30));

        A16.setBackground(new java.awt.Color(255, 255, 255));
        A16.setForeground(new java.awt.Color(0, 0, 0));
        A16.setText("C2");
        background.add(A16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, -1, 30));

        A17.setBackground(new java.awt.Color(255, 255, 255));
        A17.setForeground(new java.awt.Color(0, 0, 0));
        A17.setText("C3");
        A17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A17ActionPerformed(evt);
            }
        });
        background.add(A17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, 30));

        A56.setBackground(new java.awt.Color(255, 255, 255));
        A56.setForeground(new java.awt.Color(0, 0, 0));
        A56.setText("C4");
        background.add(A56, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, 30));

        A18.setBackground(new java.awt.Color(255, 255, 255));
        A18.setForeground(new java.awt.Color(0, 0, 0));
        A18.setText("C5");
        background.add(A18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, 30));

        A19.setBackground(new java.awt.Color(255, 255, 255));
        A19.setForeground(new java.awt.Color(0, 0, 0));
        A19.setText("C6");
        A19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A19ActionPerformed(evt);
            }
        });
        background.add(A19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, 30));

        A20.setBackground(new java.awt.Color(255, 255, 255));
        A20.setForeground(new java.awt.Color(0, 0, 0));
        A20.setText("C7");
        background.add(A20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, 30));

        A21.setBackground(new java.awt.Color(255, 255, 255));
        A21.setForeground(new java.awt.Color(0, 0, 0));
        A21.setText("C8");
        background.add(A21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, 30));

        FondoAvion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Fondo Vuelo.png"))); // NOI18N
        background.add(FondoAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A6ActionPerformed

    private void A10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A10ActionPerformed

    private void A12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A12ActionPerformed

    private void A17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A17ActionPerformed

    private void A19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A19ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A10;
    private javax.swing.JButton A11;
    private javax.swing.JButton A12;
    private javax.swing.JButton A13;
    private javax.swing.JButton A15;
    private javax.swing.JButton A16;
    private javax.swing.JButton A17;
    private javax.swing.JButton A18;
    private javax.swing.JButton A19;
    private javax.swing.JButton A2;
    private javax.swing.JButton A20;
    private javax.swing.JButton A21;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A54;
    private javax.swing.JButton A55;
    private javax.swing.JButton A56;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton A9;
    private javax.swing.JLabel FondoAvion;
    private javax.swing.JPanel background;
    // End of variables declaration//GEN-END:variables
}
