/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;


import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Quintero Pinto
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        this.setTitle("Registro");
        setLocationRelativeTo(null);
        cargarNacionalidades();
        aplicarFiltroNumeros();
    }
    
    private void aplicarFiltroNumeros() {

        javax.swing.text.AbstractDocument document = (javax.swing.text.AbstractDocument) cedulatext.getDocument();
        
        document.setDocumentFilter(new DocumentFilter() {
            @Override
            public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                if (string.matches("[0-9]*")) { 
                    super.insertString(fb, offset, string, attr);
                }
            }

            @Override
            public void replace(FilterBypass fb, int offset, int length, String string, AttributeSet attrs) throws BadLocationException {
                if (string.matches("[0-9]*")) { 
                    super.replace(fb, offset, length, string, attrs);
                }
            }
        });
    }

   private void cargarNacionalidades() {
        String query = "SELECT nombre_pais FROM nacionalidades";  // Consulta SQL

        List<String> nacionalidades = new ArrayList<>();  // Lista para almacenar los países
    
        try (Connection conn = ConexionBD.getConexion(); 
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {

            // Llenar la lista de nacionalidades con los países obtenidos de la consulta
            while (rs.next()) {
                nacionalidades.add(rs.getString("nombre_pais"));
            }

            // Cargar los países al JComboBox
            for (String pais : nacionalidades) {
                comboBoxNacionalidades.addItem(pais);
            }

        } catch (SQLException e) {
            // Si ocurre un error, mostrar un mensaje
            JOptionPane.showMessageDialog(this, "Error al cargar las nacionalidades: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();  // Imprime el detalle del error en la consola
        }
        
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulousuario = new javax.swing.JLabel();
        titulonombre = new javax.swing.JLabel();
        titulonacionalidad = new javax.swing.JLabel();
        titulocontraseña = new javax.swing.JLabel();
        nombreusuariotext = new javax.swing.JTextField();
        nombretext = new javax.swing.JTextField();
        titulocedula = new javax.swing.JLabel();
        cedulatext = new javax.swing.JTextField();
        tituloemail = new javax.swing.JLabel();
        emailtext = new javax.swing.JTextField();
        titulorepetir = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        contraseña2 = new javax.swing.JPasswordField();
        contraseña1 = new javax.swing.JPasswordField();
        comboBoxNacionalidades = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icono.png"))); // NOI18N

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/titulo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("¿Ya tienes una cuenta?");

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Inicia Sesion");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(logo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 500));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FORMULARIO REGISTRO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(66, 66, 66))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 570, -1));

        titulousuario.setBackground(new java.awt.Color(255, 255, 255));
        titulousuario.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        titulousuario.setForeground(new java.awt.Color(0, 0, 0));
        titulousuario.setText("NOMBRE USUARIO");
        jPanel1.add(titulousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 210, 30));

        titulonombre.setBackground(new java.awt.Color(255, 255, 255));
        titulonombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        titulonombre.setForeground(new java.awt.Color(0, 0, 0));
        titulonombre.setText("NOMBRE COMPLETO");
        jPanel1.add(titulonombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 210, 30));

        titulonacionalidad.setBackground(new java.awt.Color(255, 255, 255));
        titulonacionalidad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        titulonacionalidad.setForeground(new java.awt.Color(0, 0, 0));
        titulonacionalidad.setText("NACIONALIDAD");
        jPanel1.add(titulonacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 160, 30));

        titulocontraseña.setBackground(new java.awt.Color(255, 255, 255));
        titulocontraseña.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        titulocontraseña.setForeground(new java.awt.Color(0, 0, 0));
        titulocontraseña.setText("CONTRASEÑA");
        jPanel1.add(titulocontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 210, 30));

        nombreusuariotext.setBackground(new java.awt.Color(255, 255, 255));
        nombreusuariotext.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        nombreusuariotext.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nombreusuariotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 230, 30));

        nombretext.setBackground(new java.awt.Color(255, 255, 255));
        nombretext.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        nombretext.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nombretext, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 172, 230, 30));

        titulocedula.setBackground(new java.awt.Color(255, 255, 255));
        titulocedula.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        titulocedula.setForeground(new java.awt.Color(0, 0, 0));
        titulocedula.setText("CEDULA");
        jPanel1.add(titulocedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 210, 30));

        cedulatext.setBackground(new java.awt.Color(255, 255, 255));
        cedulatext.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        cedulatext.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(cedulatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 230, 30));

        tituloemail.setBackground(new java.awt.Color(255, 255, 255));
        tituloemail.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        tituloemail.setForeground(new java.awt.Color(0, 0, 0));
        tituloemail.setText("EMAIL");
        jPanel1.add(tituloemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 230, 30));

        emailtext.setBackground(new java.awt.Color(255, 255, 255));
        emailtext.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        emailtext.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 230, 30));

        titulorepetir.setBackground(new java.awt.Color(255, 255, 255));
        titulorepetir.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        titulorepetir.setForeground(new java.awt.Color(0, 0, 0));
        titulorepetir.setText("REPETIR CONTRASEÑA");
        jPanel1.add(titulorepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 220, 30));

        guardar.setBackground(new java.awt.Color(255, 255, 204));
        guardar.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        guardar.setForeground(new java.awt.Color(0, 0, 0));
        guardar.setText("GUARDAR");
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarMouseExited(evt);
            }
        });
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guardarKeyPressed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        contraseña2.setBackground(new java.awt.Color(255, 255, 255));
        contraseña2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 230, 30));

        contraseña1.setBackground(new java.awt.Color(255, 255, 255));
        contraseña1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 230, 30));

        comboBoxNacionalidades.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxNacionalidades.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        comboBoxNacionalidades.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(comboBoxNacionalidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseEntered
        guardar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_guardarMouseEntered

    private void guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseExited
        guardar.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));         // TODO add your handling code here:
    }//GEN-LAST:event_guardarMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        login n = new login();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        
        if (validarCampos()){
            
            guardarUsuario();
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void guardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guardarKeyPressed
        guardar.doClick();
    }//GEN-LAST:event_guardarKeyPressed

     private boolean validarCampos() {
        // Obtener los valores de los campos
        String nombre = nombretext.getText();
        String correo = emailtext.getText();
        String contrasena = contraseña1.getText();
        String repetirContrasena = contraseña2.getText();

        // Comprobar si algún campo está vacío
        if (nombre.isEmpty() || correo.isEmpty() || contrasena.isEmpty() || repetirContrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos.", "Error", JOptionPane.ERROR_MESSAGE);
            return false; // Devuelve falso si algún campo está vacío
        }

        // Comprobar si las contraseñas coinciden
        if (!contrasena.equals(repetirContrasena)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden. Por favor, verifica.", "Error", JOptionPane.ERROR_MESSAGE);
            return false; // Devuelve falso si las contraseñas no coinciden
        }

        // Si todas las comprobaciones son correctas, devolver verdadero
        return true;
    }
    
     
    private void guardarUsuario() {
        String nombreUsuario = nombreusuariotext.getText(); // Nombre de usuario
        String nombre = nombretext.getText();               // Nombre completo
        String correo = emailtext.getText();               // Correo electrónico
        String contrasena = new String(contraseña1.getPassword()); // Contraseña
        String cedula = cedulatext.getText();               // Cédula
        String nacionalidad = (String) comboBoxNacionalidades.getSelectedItem(); // Nacionalidad seleccionada

        // Verificar que todos los campos estén llenos
        if (nombreUsuario.isEmpty() || nombre.isEmpty() || correo.isEmpty() || contrasena.isEmpty() || cedula.isEmpty() || nacionalidad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar si el nombre de usuario, correo o cédula ya existe
        if (existeUsuario(nombreUsuario, correo, cedula)) {
            return; // Si alguno existe, no continuar con la inserción
        }

        // Realiza la conexión y guardado en la base de datos
        try (Connection conn = ConexionBD.getConexion()) {
            String query = "INSERT INTO usuarios (nombre_usuario, nombre, correo, contrasena, cedula, nacionalidad) VALUES (?, ?, ?, ?, ?, ?)";
            try (PreparedStatement stmt = conn.prepareStatement(query)) {
                stmt.setString(1, nombreUsuario);      // Set nombre de usuario
                stmt.setString(2, nombre);             // Set nombre completo
                stmt.setString(3, correo);             // Set correo
                stmt.setString(4, contrasena);         // Set contraseña
                stmt.setString(5, cedula);             // Set cédula
                stmt.setString(6, nacionalidad);       // Set nacionalidad

                int rowsInserted = stmt.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Usuario guardado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el usuario: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean existeUsuario(String nombreUsuario, String correo, String cedula) {
    try (Connection conn = ConexionBD.getConexion()) {
        // Consulta para verificar si el nombre de usuario ya existe
        String query = "SELECT COUNT(*) FROM usuarios WHERE nombre_usuario = ? OR correo = ? OR cedula = ?";
        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, nombreUsuario);
            stmt.setString(2, correo);
            stmt.setString(3, cedula);

            ResultSet rs = stmt.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, "El nombre de usuario, correo o cédula ya está registrado.", "Error", JOptionPane.ERROR_MESSAGE);
                return true;  // Si algún campo ya existe, retornar true
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al verificar los datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    return false; // Si no se encontró nada, retornar false
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedulatext;
    private javax.swing.JComboBox<String> comboBoxNacionalidades;
    private javax.swing.JPasswordField contraseña1;
    private javax.swing.JPasswordField contraseña2;
    private javax.swing.JTextField emailtext;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nombretext;
    private javax.swing.JTextField nombreusuariotext;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulocedula;
    private javax.swing.JLabel titulocontraseña;
    private javax.swing.JLabel tituloemail;
    private javax.swing.JLabel titulonacionalidad;
    private javax.swing.JLabel titulonombre;
    private javax.swing.JLabel titulorepetir;
    private javax.swing.JLabel titulousuario;
    // End of variables declaration//GEN-END:variables
}
